# Generated by Django 5.2.14 on 2026-05-23 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0010_alter_pedido_metodo_pago'),
        ('usuarios', '0002_alter_usuario_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Fondo Inicial Gs.')),
                ('apertura_en', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('cierre_en', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('notas_apertura', models.TextField(blank=True, default='')),
                ('notas_cierre', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario', verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'db_table': 'caja_sesiones',
                'ordering': ['-apertura_en'],
            },
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_inicial', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_ventas_tarjeta', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_ventas_transferencia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_ventas_qr', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_ingresos_extra', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_retiros', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_propinas', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_ventas', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('denominaciones', models.JSONField(blank=True, null=True, verbose_name='Conteo de billetes/monedas')),
                ('total_contado_efectivo', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Efectivo contado físicamente')),
                ('total_esperado', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Diferencia (sobrante+/faltante-)')),
                ('tipo_diferencia', models.CharField(blank=True, choices=[('', 'Sin diferencia'), ('sobrante', 'Sobrante'), ('faltante', 'Faltante')], default='', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='caja.cajasession')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'db_table': 'caja_cortes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('ingreso_extra', 'Ingreso Extra'), ('retiro', 'Retiro'), ('ajuste', 'Ajuste')], default='venta', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('mixto', 'Mixto')], default='efectivo', max_length=20)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(default='PYG', max_length=10)),
                ('monto_pyg', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto en Gs.')),
                ('detalle_pagos', models.JSONField(blank=True, null=True, verbose_name='Detalle de pagos mixtos')),
                ('motivo', models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo (retiros/ingresos)')),
                ('propina', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Propina')),
                ('vuelto', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Vuelto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='pedidos.pedido')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.cajasession')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'caja_movimientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
