# Generated by Django 5.2.15 on 2026-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajasession',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja_sesiones', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cortes_caja', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='tenants.restaurante'),
        ),
    ]
