# Generated by Django 5.2.13 on 2026-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
