# Generated by Django 5.2.15 on 2026-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('usuarios', '0003_usuario_email_usuario_ultimo_acceso_sesiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='tenants.restaurante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('restaurante', 'pin')},
        ),
    ]
