# Generated by Django 5.2.13 on 2026-05-01 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('estado', models.CharField(choices=[('demo', 'Demo'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='demo', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_expedicion', models.CharField(default='001', max_length=3)),
                ('numero_inicio', models.IntegerField()),
                ('numero_fin', models.IntegerField()),
                ('numero_actual', models.IntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'db_table': 'timbrados',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('ruc_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('xml', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
