# Generated by Django 5.2.14 on 2026-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='punto_expedicion',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='timbrado_numero',
            field=models.CharField(default='001-001-0000001', max_length=20),
        ),
    ]
