# Generated by Django 5.2.14 on 2026-05-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_configuracion_establecimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('etiqueta', models.CharField(max_length=100)),
                ('icono', models.CharField(default='payments', max_length=50)),
                ('color', models.CharField(default='#4CAF50', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['orden'],
            },
        ),
    ]
