# Generated by Django 5.2.14 on 2026-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='ambiente_sifen',
            field=models.CharField(choices=[('test', 'Pruebas'), ('produccion', 'Producción')], default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='certificado_pkcs12',
            field=models.FileField(blank=True, help_text='Certificado digital .p12 para firma de facturas electrónicas', null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='csc',
            field=models.CharField(blank=True, help_text='Código de Seguridad del Contribuyente (CSC) para SIFEN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='csc_pin',
            field=models.CharField(blank=True, help_text='PIN del CSC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, help_text='Código de Control del Documento Electrónico (SIFEN)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='protocolo',
            field=models.TextField(blank=True, help_text='Respuesta XML del protocolo de aprobación SIFEN', null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado a SIFEN'), ('aprobado', 'Aprobado por SIFEN'), ('rechazado', 'Rechazado por SIFEN'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='xml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
