# Generated by Django 5.2.14 on 2026-05-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_configuracion_ambiente_sifen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='cCiuEmi',
            field=models.CharField(default='1', help_text='Código de ciudad/distrito', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='cDepEmi',
            field=models.CharField(default='1', help_text='Código de departamento (SIFEN: 1=Capital, 2=Concepción, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='cDirEmi',
            field=models.TextField(blank=True, default='', help_text='Dirección fiscal del emisor (para SIFEN)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dDesCiuEmi',
            field=models.CharField(default='ASUNCION (DISTRITO)', help_text='Descripción de la ciudad/distrito', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dDesDepEmi',
            field=models.CharField(default='CAPITAL', help_text='Descripción del departamento', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dEmailE',
            field=models.EmailField(blank=True, default='', help_text='Email del emisor', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dNumCas',
            field=models.IntegerField(default=0, help_text='Número de casa del emisor'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='gActEco_codigo',
            field=models.CharField(default='47111', help_text='Código de actividad económica (SIFEN)', max_length=10),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='gActEco_descripcion',
            field=models.CharField(default='Venta al por menor en comercios no especializados', help_text='Descripción de la actividad económica', max_length=255),
        ),
    ]
