# Generated by Django 5.2.13 on 2026-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_factura_kude_qr_sifen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='cDepEmi',
            field=models.CharField(default='1', help_text='Código de departamento (SIFEN)', max_length=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cdc',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Código de Control'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='protocolo',
            field=models.TextField(blank=True, default='', verbose_name='Protocolo SIFEN'),
        ),
    ]
