# Generated by Django 5.2.15 on 2026-07-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_configuracion_cdepemi_alter_factura_cdc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tamano_papel',
            field=models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='58mm', help_text='Tamaño de papel para impresión térmica', max_length=4),
        ),
    ]
