# Generated by Django 5.2.16 on 2026-07-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_configuracion_tamano_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='sifen_habilitado',
            field=models.BooleanField(default=False, help_text='Habilitar facturación electrónica SIFEN'),
        ),
    ]
