# Generated by Django 5.2.16 on 2026-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_configuracion_sifen_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='csc_id',
            field=models.IntegerField(default=1, help_text='ID del CSC (1 o 2) - identifica cuál CSC está activo'),
        ),
    ]
