# Generated by Django 5.2.15 on 2026-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_configuracion_csc_id'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='factura',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timbrados', to='tenants.restaurante'),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='metodopago',
            unique_together={('restaurante', 'nombre')},
        ),
    ]
