# Generated by Django 5.2.13 on 2026-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
