# Generated by Django 5.2.13 on 2026-05-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='propina',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cocinando', 'Cocinando'), ('listo', 'Listo'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('qr', 'QR'), ('mixto', 'Mixto')], default='efectivo', max_length=50),
        ),
    ]
