# Generated by Django 5.2.14 on 2026-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_propina_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='Consumidor Final', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_ruc',
            field=models.CharField(default='44444444-7', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_tipo',
            field=models.CharField(default='consumidor', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='generar_comanda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='generar_factura',
            field=models.BooleanField(default=False),
        ),
    ]
