# Generated by Django 5.2.14 on 2026-05-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_cliente_nombre_pedido_cliente_ruc_and_more'),
        ('usuarios', '0002_alter_usuario_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comanda', 'Comanda'), ('factura', 'Factura'), ('ticket', 'Ticket')], max_length=20)),
                ('numero_impresion', models.IntegerField(default=1)),
                ('impresion_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impresiones', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Impresión',
                'verbose_name_plural': 'Impresiones',
                'db_table': 'impresiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
