# Generated by Django 5.2.14 on 2026-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_impresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('venta_rapida', 'Venta Rápida'), ('delivery', 'Delivery')], default='mesa', max_length=20),
        ),
    ]
