# Generated by Django 5.2.14 on 2026-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_tipo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('mesa', 'Mesa'), ('venta', 'Venta'), ('delivery', 'Delivery')], default='mesa', max_length=20),
        ),
    ]
