# Generated by Django 5.2.14 on 2026-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_update_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_nro',
            field=models.CharField(blank=True, help_text='Numero de comprobante/operacion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuotas',
            field=models.IntegerField(default=1, help_text='Cantidad de cuotas'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='marca_qr',
            field=models.CharField(blank=True, help_text='Tigo Money, Personal Pay, Bancard QR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='marca_tarjeta',
            field=models.CharField(blank=True, help_text='Visa, Mastercard, Cabal, Amex', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ultimos_4',
            field=models.CharField(blank=True, help_text='Ultimos 4 digitos de tarjeta', max_length=4, null=True),
        ),
    ]
