# Generated by Django 5.2.14 on 2026-05-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_comprobante_nro_pedido_cuotas_pedido_marca_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle_pagos',
            field=models.JSONField(blank=True, help_text='Array de pagos: [{metodo, moneda, monto, monto_pyg}]', null=True),
        ),
    ]
