# Generated by Django 5.2.14 on 2026-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_detalle_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=50),
        ),
    ]
