# Generated by Django 5.2.14 on 2026-05-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_pedido_detalle_pagos'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_realizados', to='usuarios.usuario'),
        ),
    ]
