# Generated by Django 5.2.14 on 2026-05-24 03:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_pedido_numero_factura'),
        ('usuarios', '0002_alter_usuario_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=50),
        ),
        migrations.CreateModel(
            name='CajaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('arqueo', models.JSONField(blank=True, help_text='Conteo por denominación: [{denominacion, cantidad, subtotal}]', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_caja', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'db_table': 'caja_turnos',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
