# Generated by Django 5.2.13 on 2026-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_merge_20260525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cajero',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero_factura',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado_en_estado',
            field=models.CharField(blank=True, help_text='Estado en el que estaba cuando se cancelo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de cancelacion texto libre', null=True),
        ),
        migrations.DeleteModel(
            name='CajaTurno',
        ),
    ]
