# Generated by Django 5.2.16 on 2026-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_remove_pedido_cajero_remove_pedido_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_iva',
            field=models.IntegerField(default=10, help_text='Tasa de IVA aplicada al cobro (0, 5, 10)'),
        ),
    ]
