# Generated by Django 5.2.15 on 2026-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_tipo_iva'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impresiones', to='tenants.restaurante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tenants.restaurante'),
        ),
        migrations.AlterField(
            model_name='impresion',
            name='impresion_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='impresion',
            unique_together={('restaurante', 'impresion_id')},
        ),
    ]
