# Generated by Django 5.2.15 on 2026-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Básico'), ('pro', 'Pro')], default='free', max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'db_table': 'restaurantes',
            },
        ),
    ]
