# Generated by Django 5.2.16 on 2026-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rls_restaurantes_y_django'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='estado_licencia',
            field=models.CharField(choices=[('activo', 'Activo'), ('expirado', 'Expirado'), ('suspended', 'Suspendido')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
