# Generated by Django 5.2.16 on 2026-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen_archivo_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.IntegerField(choices=[(0, 'Exento'), (5, '5%'), (10, '10%'), (15, '15%')], default=10, help_text='Tasa de IVA aplicable al producto'),
        ),
    ]
