# Generated by Django 5.2.13 on 2026-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='area',
            field=models.CharField(choices=[('principal', 'Principal'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('patio', 'Patio')], default='principal', max_length=50),
        ),
        migrations.AddField(
            model_name='mesa',
            name='comensales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('limpiezar', 'Limpieza')], default='disponible', max_length=20),
        ),
    ]
