# Generated by Django 5.2.15 on 2026-07-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0003_alter_mesa_estado'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='tenants.restaurante'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('restaurante', 'numero')},
        ),
    ]
